import { RecommendationList } from "@/components/recommendations/recommendation-list";

export default function RecommendationsPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div>
        <h1 className="text-2xl font-semibold text-slate-900">AI Recommendations</h1>
        <p className="mt-1 text-sm text-slate-500">
          Review actionable insights generated by our machine learning models. 
          The AI continually analyzes your campaign performance to lower your cost per lead.
        </p>
      </div>
      
      <RecommendationList />
    </div>
  );
}
